# 站点基本信息
title: 任亚墨的书房
description: 你似乎来过这里……
baseurl: "" 
url: "https://reqeekouton.github.io"

# 作者信息
author:
  name: "任亚墨"
  email: "public_rymingenu@hotmail.com"

# 社交媒体链接
social:
  twitter: "Rymingenu"
  github: "Reqeekouton"

# 站点设置
markdown: kramdown
highlighter: rouge

# Permalink 设置
permalink: /:categories/:title.md

# 文件处理
exclude: 
  - README.md

# 插件配置
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 自定义变量
custom:
  github_repo: "https://github.com/Reqeekouton/reqeekouton.github.io" # GitHub 仓库链接
  version: "0.0.1-alpha" # 站点或项目的版本号
