# 站点基本信息
title: 任亚墨的书房
description: 你似乎来过这里……
baseurl: "" 
url: "https://rymingenu.top"

# 作者信息
author:
  name: "任亚墨"
  email: "rymingenu@outlook.com"

# 社交媒体链接
social:
  twitter: "任亚墨"
  github: "Reqeekouton"

# 站点设置
markdown: kramdown
highlighter: rouge

# Permalink 设置
permalink: /:categories/:title

# 文件处理
exclude: 
  - README.md

# 插件配置
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

jekyll-archives:
  enabled:
    - tags
  layouts: 
    tag: tag
  permalinks:
    tag: /tag/:name/

paginate: 5
paginate_path: "/page:num/"
    
# 自定义变量
custom:
  github_repo: "https://github.com/Reqeekouton/reqeekouton.github.io" # GitHub 仓库链接
  version: "1.0" # 站点或项目的版本号

