# Setup
title:               '任亚墨的书房'
tagline:             ''
description:         '仍然处于测试'
url:                 https://reqeekouton.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              任亚墨
  url:     
  email: 

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id:
